config/routes.rb
Rails.application.routes.draw do
  devise_for :users


  resources :services

  get "home/index", :as => "user_root"

  get "home/login"

  get "home/send_report"

  put "checkins/split_room" => "checkins#split_room", :as => "split_room"

  get "/checkout/:id" => "checkins#checkout"

  resources :checkins

  resources :rooms

  resources :room_types

  resources :guests
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, :only => ['index']

  def index
    @rooms = Room.paginate :page => params[:page],:order => "id"
    @rooms_available = Room.available
    @room_checkin = Hash.new
    Checkin.where("status is NULL").each do |c|
      c.line_items.each do |li|
        if not li.freez 
          @room_checkin[li.room] = c
        end
      end
    end

  end

  def login
    respond_to do |format|
      format.html { 
        if user_signed_in?
          redirect_to user_root_path
        else
          render :layout => 'user'
        end
      }
    end
    
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="block-border">
  <div class="block-content" style="overflow:auto;padding-top:5px;background:#aaa;">
    <div class="block-controls">
      <%= will_paginate @rooms  %>
    </div>
    <div id="panel-frame" style="width:49%">
      <div class="panel">
        <div class="head">
          <a class="close" href="#">close</a>
        </div>
        <div class="data"></div>
      </div>
    </div>
    <div class="left no-margin" style="width:51%">
      <%= render :partial => "shared/roomtable" %>
    </div>
    <div class="right" style="width:50%;">
      <h3>Welcome to Hotel Management Home Page</h3>
      <hr/>
      <%= render :partial => "shared/charts" %>
    </div>
  </div>
</div>
<div id="service_dialog" style="display:none" title="Add Service">
  <%= render :partial => "service_items/service_item_form" %>
</div>
<div id="payment_dialog" style="display:none" title="Add Payments">
  <%= render :partial => "payments/payment_form" %>
</div>
<div id="checkout_dialog" style="display:none;" title="Checkout">
  <div id="pending_amount_div"></div>
  <div id="checkout_form_div"></div>
</div>
<div id="splitroom_dialog" style="display:none;" title="Split Room as New Checkin">
  Do you want to split Room -
  <span id="split_room_number"></span>
  into separate checkin?
  <%= form_tag split_room_url,:id => :splitroom_form, :method => :put do %>
    <%= hidden_field_tag :splitroom_line_item_id %>
  <% end %>
</div>
<div id="delete_room_service_dialog" style="display:none;" title="Delete Room Service">
  Do you want to delete Room Service
  <span id="delete_room_service"></span>
  Item?
  <%= form_tag delete_service_url, :id => "delete_service_form", :method => :delete, :remote => true do %>
    <%= hidden_field_tag "delete_service_item_id" %>
  <% end %>
</div>
<div id="delete_payment_dialog" style="display:none;" title="Delete Payment">
  Do you want to delete Payment
  <span id="delete_payment"></span>
  Item?
  <%= form_tag delete_payment_url, :id => "delete_payment_form", :method => :delete, :remote => true do %>
    <%= hidden_field_tag "delete_payment_id" %>
  <% end %>
</div>
<div id="shiftroom_dialog" style="display:none" title="Shift Room">
  <%= form_tag shift_room_url, :id => :shiftroom_form, :method => :put do %>
    <%= hidden_field_tag :shiftroom_room_id_checkin_id %>
    <%= label_tag "Shift to:" %>
    <%= select_tag :shift_room_id, options_from_collection_for_select(@rooms_available,:id,:roomtype) %>
    <br/>
    <%= label_tag "Rate" %>
    <%= text_field_tag :rate %>
    <br/>
    <%= label_tag "tax" %>
    <%= text_field_tag :tax %>
    \%
    <br/>
    <%= label_tag "Time of Shift" %>
    <%= time_select :shift_room,"shift_time" %>
  <% end %>
</div>
<div id="edit_line_item_dialog" style="display:none" title="Edit Checkin">
  <div id="line_item_form"></div>
</div>
<div id="block_room_dialog" style="display:none" title="Block Room?">
  Do you want to block Room -
  <span id="block_room_number"></span>
  &nbsp;?
  <%= form_tag block_room_url,:id => :block_room_form, :method => :put do %>
    <%= label_tag "Specify Reason" %>
    <%= select_tag "reason",options_for_select(["Maintenance","Occupied by Staff"]) %>
    <%= hidden_field_tag :block_room_id %>
  <% end %>
</div>
<div id="unblock_room_dialog" style="display:none" title="Unblock Room?">
  Do you want to unblock Room -
  <span id="unblock_room_number"></span>
  &nbsp;?
  <%= form_tag unblock_room_url,:id => :unblock_room_form, :method => :put do %>
    <%= hidden_field_tag :unblock_room_id %>
  <% end %>
</div>
<div id="add_company_dialog" style="display:none" title="Add Company/Guests">
  Add Guest
</div>


<script type="text/javascript">
  $('#service_form').bind("ajax:loading",  function(){
    $('.add_service').after('<div id="loading"><img style = "float:right;margin:3px;" src="/images/smallloading.gif"/></div>')
  });
  $('#payment_form').bind("ajax:loading",  function(){
    $('.add_payment').after('<div id="loading"><img style = "float:right;margin:3px;" src="/images/smallloading.gif"/></div>')
  });
  $('#delete_service_form').bind("ajax:loading",  function(){
    $('.add_service').after('<div id="loading"><img style = "float:right;margin:3px;" src="/images/smallloading.gif"/></div>')
  });
  $('#edit_line_item_form').bind("ajax:loading",  function(){
    $('#line_items').html('<div id="loading"><img style = "float:right;margin:3px;" src="/images/smallloading.gif"/></div>')
  });

  $(document).ready(function() {

    $('.shiftroom_link').click(function(){
      $('#shiftroom_dialog').dialog('open');
      $('#shiftroom_room_id_checkin_id').val($(this).parents('tr').attr('id'));
      return false;
     });

    $('.blockroom_link').click(function(){
      $('#block_room_dialog').dialog('open');
      $('#block_room_id').val($(this).attr('id').split('-')[1]);
      $('#block_room_number').html($(this).parents('.block').find('th[scope=row]').text());
      return false;
     });

    $('.unblockroom_link').click(function(){
      $('#unblock_room_dialog').dialog('open');
      $('#unblock_room_id').val($(this).attr('id').split('-')[1]);
      $('#unblock_room_number').html($(this).parents('.block').find('th[scope=row]').text());
      return false;
     });

    $('.checkedin').click(function(){

      var id= $(this).parents('tr').attr('id');
      myarr = id.split('-');
      $('#service_item_room_id').val(myarr[1]);
      var data_id= $(".data").attr('id');
      if(data_id == ''){
        $('.data').attr('id','data' + id);
      }
      var panel= $('.panel');
      var panel_width=$('.panel').css('left');

      if(data_id == 'data' + id){
        panel.animate({left: parseInt(panel.css('left'),0) == 0 ? +panel.outerWidth() : 0});
      }
      else{
        $('.data').attr('id','data' + id);
        if(panel_width =='465px'){

        }
        else{
          panel.animate({left: parseInt(panel.css('left'),0) == 0 ? +panel.outerWidth() : 0});
        }
        $.ajax({
          beforeSend: function(){$('.data').html('<div style="margin:100px";><img src="/images/smallloading.gif"/>&nbsp;<b>Loading..</b></div>');},
          url: '/checkins/' + myarr[3]
        });
      }
      return false;
    });

    $('.close').click(function(){
      var panel= $('.panel');
      panel.animate({left: parseInt(panel.css('left'),0) == 0 ? +panel.outerWidth() : 0});
      return false;
    });
  });
     
  
  $('#checkout_dialog').dialog({
    autoOpen: false,
    width: 400,
    buttons: {
      "Save": function() { 
        $(this).dialog("close"); 
        $('#checkout_dialog form').submit();
        window.open('/checkout/' + $('#service_item_checkin_id').val(),'Check Out', 'height=400,width=400');
        window.location="/home/index";
      }, 
      "Cancel": function() { 
        $(this).dialog("close"); 
      } 
    }
  });
  $('#service_dialog').dialog({
    autoOpen: false,
    width: 400,
    buttons: {
      "Save": function() { 
        $(this).dialog("close"); 
        $('#service_form').submit();
      }, 
      "Cancel": function() { 
        $(this).dialog("close"); 
      } 
    }
  });
  $('#payment_dialog').dialog({
    autoOpen: false,
    width: 400,
    buttons: {
      "Save": function() { 
        $(this).dialog("close"); 
        $('#payment_form').submit();
      }, 
      "Cancel": function() { 
        $(this).dialog("close"); 
      } 
    }
  });

  $('#splitroom_dialog').dialog({
    autoOpen: false,
    width: 400,
    buttons: {
      "Yes": function() { 
        $(this).dialog("close"); 
        $('#splitroom_form').submit();
      }, 
      "No": function() { 
        $(this).dialog("close"); 
      } 
    }
  });
  $('#delete_room_service_dialog').dialog({
    autoOpen: false,
    width: 400,
    buttons: {
      "Yes": function() { 
        $(this).dialog("close"); 
        $('#delete_service_form').submit();
      }, 
      "No": function() { 
        $(this).dialog("close"); 
      } 
    }
  });
  $('#shiftroom_dialog').dialog({
    autoOpen: false,
    width: 400,
    buttons: {
      "Shift": function() { 
        $(this).dialog("close"); 
        $('#shiftroom_form').submit();
      }, 
      "Cancel": function() { 
        $(this).dialog("close"); 
      } 
    }
  });

  $('#delete_payment_dialog').dialog({
    autoOpen: false,
    width: 400,
    buttons: {
      "Yes": function() { 
        $(this).dialog("close"); 
        $('#delete_payment_form').submit();
      }, 
      "No": function() { 
        $(this).dialog("close"); 
      } 
    }
  });
  $('#edit_line_item_dialog').dialog({
    autoOpen: false,
    width: 450,
    buttons: {
      "Save": function() { 
        $(this).dialog("close"); 
        $('#edit_line_item_form').submit();
      }, 
      "Cancel": function() { 
        $(this).dialog("close"); 
      } 
    }
  });
  $('#block_room_dialog').dialog({
    autoOpen: false,
    width: 450,
    buttons: {
      "Save": function() { 
        $(this).dialog("close"); 
        $('#block_room_form').submit();
      }, 
      "Cancel": function() { 
        $(this).dialog("close"); 
      } 
    }
  });
  $('#unblock_room_dialog').dialog({
    autoOpen: false,
    width: 450,
    buttons: {
      "Save": function() { 
        $(this).dialog("close"); 
        $('#unblock_room_form').submit();
      }, 
      "Cancel": function() { 
        $(this).dialog("close"); 
      } 
    }
  });
</script>